-- Acessível somente na conexão atual
CREATE TABLE #TABELA01 (
	ID VARCHAR(10),
	NOME VARCHAR(30)
);

INSERT INTO #TABELA01
VALUES ('1', 'JONAS');

SELECT *
FROM #TABELA01


-- Acessível través de qualquer conexão enquanto a instância não for reiniciada
CREATE TABLE ##TABELA02 (
	ID VARCHAR(10),
	NOME VARCHAR(30)
);

INSERT INTO ##TABELA02
VALUES ('1', 'JONAS');

SELECT *
FROM ##TABELA02




DECLARE @NOTAS_EXISTENTES TABLE (
	nota INT,
	status VARCHAR(20)
);

DECLARE @NUMERO_INICIAL INT, @NUMERO_FINAL INT, @TESTENOTA INT;

SET @NUMERO_INICIAL = 1;
SET @NUMERO_FINAL = 200;

SET NOCOUNT ON;

WHILE @NUMERO_INICIAL <= @NUMERO_FINAL
BEGIN
	SELECT @TESTENOTA = COUNT(*) FROM [NOTAS FISCAIS] nf WHERE nf.NUMERO = @NUMERO_INICIAL;
	IF @TESTENOTA > 0
		INSERT INTO @NOTAS_EXISTENTES VALUES (@NUMERO_INICIAL, 'É UMA NOTA FISCAL')
	ELSE
		INSERT INTO @NOTAS_EXISTENTES VALUES (@NUMERO_INICIAL, 'NÃO É NOTA FISCAL')

	SET @NUMERO_INICIAL += 1;
END

SELECT * FROM @NOTAS_EXISTENTES ne


