SET NOCOUNT ON;

DECLARE @CPF VARCHAR(11);
DECLARE @NOME VARCHAR(100);
DECLARE @NUMERO_CLIENTES INT;
DECLARE @I INT = 1;
DECLARE @MES INT;
DECLARE @ANO INT;
DECLARE @TOTAL_VENDAS FLOAT;
DECLARE @TABELA_FINAL TABLE (CPF VARCHAR(11), NOME VARCHAR(100), MES INT, ANO INT, VALOR_TOTAL FLOAT);

SELECT @NUMERO_CLIENTES = COUNT(*) FROM [TABELA DE CLIENTES] tdc

SET @ANO = 2015;
SET @MES = 1;

WHILE @I <= @NUMERO_CLIENTES
BEGIN
	SELECT @CPF = C.CPF, @NOME = C.NOME
	FROM (
		SELECT ROW_NUMBER() OVER (ORDER BY CPF) AS RowNum, *
		FROM [TABELA DE CLIENTES]
	) C
	WHERE C.RowNum = @I
	
	SELECT @TOTAL_VENDAS = SUM(I.QUANTIDADE * I.PREÇO)
	FROM [NOTAS FISCAIS] NF
	INNER JOIN [ITENS NOTAS FISCAIS] I ON I.NUMERO = NF.NUMERO
	WHERE NF.CPF = @CPF
		AND YEAR(NF.DATA) = @ANO
		AND MONTH(NF.DATA) = @MES;

	INSERT INTO @TABELA_FINAL VALUES (@CPF, @NOME, @MES, @ANO, @TOTAL_VENDAS);

	PRINT(CONCAT('CPF: ', @CPF, ' | VALOR: R$', TRIM(STR(@TOTAL_VENDAS, 15, 2)), ' | Cliente: ', @NOME))

	SET @I += 1;
END

SELECT * FROM @TABELA_FINAL;


/*
DECLARE @CODIGO VARCHAR(11);
DECLARE @NOMEPRODUTO VARCHAR(100);
DECLARE @NUMERO_PRODUTOS INT;
DECLARE @E INT = 1;

SELECT @NUMERO_PRODUTOS = COUNT(*) FROM [TABELA DE PRODUTOS] P

WHILE @E <= @NUMERO_PRODUTOS
BEGIN
	SELECT @CODIGO = C.[CODIGO DO PRODUTO], @NOMEPRODUTO = C.[NOME DO PRODUTO]
	FROM (
		SELECT ROW_NUMBER() OVER (ORDER BY [NOME DO PRODUTO]) AS RowNum, *
		FROM [TABELA DE PRODUTOS]
	) C
	WHERE C.RowNum = @E
	PRINT(CONCAT('Produto: ', @NOMEPRODUTO, ' | Código: ', @CODIGO))
	SET @E += 1;
END
*/



