DECLARE @CPF VARCHAR(11);
DECLARE @NOME VARCHAR(100);
DECLARE @NUMERO_CLIENTES INT;
DECLARE @I INT = 1;

SELECT @NUMERO_CLIENTES = COUNT(*) FROM [TABELA DE CLIENTES] tdc


WHILE @I <= @NUMERO_CLIENTES
BEGIN
	SELECT @CPF = C.CPF, @NOME = C.NOME
	FROM (
		SELECT ROW_NUMBER() OVER (ORDER BY CPF) AS RowNum, *
		FROM [TABELA DE CLIENTES]
	) C
	WHERE C.RowNum = @I
	PRINT(CONCAT('Cliente: ', @NOME, ' | CPF: ', @CPF))
	SET @I += 1;
END



/*
DECLARE @CODIGO VARCHAR(11);
DECLARE @NOMEPRODUTO VARCHAR(100);
DECLARE @NUMERO_PRODUTOS INT;
DECLARE @E INT = 1;

SELECT @NUMERO_PRODUTOS = COUNT(*) FROM [TABELA DE PRODUTOS] P

WHILE @E <= @NUMERO_PRODUTOS
BEGIN
	SELECT @CODIGO = C.[CODIGO DO PRODUTO], @NOMEPRODUTO = C.[NOME DO PRODUTO]
	FROM (
		SELECT ROW_NUMBER() OVER (ORDER BY [NOME DO PRODUTO]) AS RowNum, *
		FROM [TABELA DE PRODUTOS]
	) C
	WHERE C.RowNum = @E
	PRINT(CONCAT('Produto: ', @NOMEPRODUTO, ' | Código: ', @CODIGO))
	SET @E += 1;
END
*/



