DECLARE @LIMITE_MINIMO INT;
DECLARE @LIMITE_MAXIMO INT;
DECLARE @LIMITE_LINHAS INT;
DECLARE @QTDE_LINHAS INT;

SET @LIMITE_MINIMO = 3;
SET @LIMITE_MAXIMO = 30;
SET @LIMITE_LINHAS = 10;
SET @QTDE_LINHAS = 0;

PRINT 'Início do While'

WHILE @LIMITE_MINIMO <= @LIMITE_MAXIMO 
BEGIN
	PRINT @LIMITE_MINIMO;
	SET @QTDE_LINHAS += 1;
	SET @LIMITE_MINIMO += 1;

	IF @QTDE_LINHAS = @LIMITE_LINHAS
	BEGIN
		PRINT 'Saiu do While pelo Break'
		BREAK
	END
END;

PRINT 'Fim do While'


/* 
--- DESAFIO 01 ---

DECLARE @DATA_INICIAL DATE = '2017-07-01';
DECLARE @DATA_FINAL DATE = '2017-07-10';
DECLARE @NUMERO_NOTAS INT;

WHILE @DATA_INICIAL <= @DATA_FINAL
BEGIN
		SELECT @NUMERO_NOTAS = COUNT(*)
		FROM [NOTAS FISCAIS] nf
		WHERE nf.DATA = @DATA_INICIAL

		PRINT(CONVERT(VARCHAR(10), @DATA_INICIAL, 103) + ' - Qtde notas: ' + CONVERT(VARCHAR(10), @NUMERO_NOTAS));

		SET @DATA_INICIAL = DATEADD(DAY, 1, @DATA_INICIAL);
END

*/


IF OBJECT_ID('NOTAS_EXISTENTES', 'U') IS NOT NULL DROP TABLE NOTAS_EXISTENTES;

CREATE TABLE NOTAS_EXISTENTES (
	nota INT,
	status VARCHAR(20)
);

DECLARE @NUMERO_INICIAL INT, @NUMERO_FINAL INT, @TESTENOTA INT;

SET @NUMERO_INICIAL = 1;
SET @NUMERO_FINAL = 200;

SET NOCOUNT ON;

WHILE @NUMERO_INICIAL <= @NUMERO_FINAL
BEGIN
	SELECT @TESTENOTA = COUNT(*) FROM [NOTAS FISCAIS] nf WHERE nf.NUMERO = @NUMERO_INICIAL;
	IF @TESTENOTA > 0
		INSERT INTO NOTAS_EXISTENTES VALUES (@NUMERO_INICIAL, 'É UMA NOTA FISCAL')
	ELSE
		INSERT INTO NOTAS_EXISTENTES VALUES (@NUMERO_INICIAL, 'NÃO É NOTA FISCAL')

	SET @NUMERO_INICIAL += 1;
END

SELECT * FROM NOTAS_EXISTENTES ne


-- TSQL não tem a estrutura de repetição FOR
DECLARE @I INT;
SET @I = 1;
WHILE @I <= 100
BEGIN
	PRINT(@I)
	SET @I += 1;
END



DECLARE @NUM INT;
SET @NUM = 100;
WHILE @NUM >= 0
BEGIN
	PRINT(@NUM)
	SET @NUM -= 1;
END

