DECLARE @LIMITE_MINIMO INT;
DECLARE @LIMITE_MAXIMO INT;
DECLARE @LIMITE_LINHAS INT;
DECLARE @QTDE_LINHAS INT;

SET @LIMITE_MINIMO = 3;
SET @LIMITE_MAXIMO = 30;
SET @LIMITE_LINHAS = 10;
SET @QTDE_LINHAS = 0;

PRINT 'Início do While'

WHILE @LIMITE_MINIMO <= @LIMITE_MAXIMO 
BEGIN
	PRINT @LIMITE_MINIMO;
	SET @QTDE_LINHAS += 1;
	SET @LIMITE_MINIMO += 1;

	IF @QTDE_LINHAS = @LIMITE_LINHAS
	BEGIN
		PRINT 'Saiu do While pelo Break'
		BREAK
	END
END;

PRINT 'Fim do While'


/* 
--- DESAFIO 01 ---

DECLARE @DATA_INICIAL DATE = '2017-07-01';
DECLARE @DATA_FINAL DATE = '2017-07-10';
DECLARE @NUMERO_NOTAS INT;

WHILE @DATA_INICIAL <= @DATA_FINAL
BEGIN
		SELECT @NUMERO_NOTAS = COUNT(*)
		FROM [NOTAS FISCAIS] nf
		WHERE nf.DATA = @DATA_INICIAL

		PRINT(CONVERT(VARCHAR(10), @DATA_INICIAL, 103) + ' - Qtde notas: ' + CONVERT(VARCHAR(10), @NUMERO_NOTAS));

		SET @DATA_INICIAL = DATEADD(DAY, 1, @DATA_INICIAL);
END

*/


IF OBJECT_ID('NOTAS_EXISTENTES', 'U') IS NOT NULL DROP TABLE NOTAS_EXISTENTES;

CREATE TABLE NOTAS_EXISTENTES (
	nota INT,
	status VARCHAR(20)
);

