SELECT *
FROM TABELA_DE_CLIENTES
WHERE 1 = 1;

SELECT  *
FROM TABELA_DE_CLIENTES
WHERE 1 = 0;

SELECT *
FROM TABELA_DE_PRODUTOS
WHERE CODIGO_DO_PRODUTO = '1002767';

SELECT *
FROM TABELA_DE_PRODUTOS
WHERE SABOR = 'Laranja';

-- Colation de case insensitive
SELECT *
FROM TABELA_DE_PRODUTOS
WHERE EMBALAGEM = 'pet';


SELECT *
FROM TABELA_DE_PRODUTOS
WHERE PRECO_DE_LISTA > 10;

SELECT *
FROM TABELA_DE_PRODUTOS
WHERE PRECO_DE_LISTA BETWEEN 5 AND 10;

SELECT *
FROM TABELA_DE_CLIENTES
WHERE IDADE != 18;

------------------------------------------

SELECT *
FROM TABELA_DE_PRODUTOS
WHERE SABOR = 'Manga'
	AND TAMANHO = '470 ml'


SELECT *
FROM TABELA_DE_PRODUTOS
WHERE NOT (SABOR = 'Manga'
	OR TAMANHO = '470 ml')

SELECT *
FROM TABELA_DE_PRODUTOS
WHERE SABOR IN ('Manga', 'Laranja', 'Melancia')


SELECT *
FROM TABELA_DE_PRODUTOS
WHERE SABOR IN ('Manga', 'Laranja', 'Melancia')
	AND TAMANHO = '1 Litro'

SELECT *
FROM TABELA_DE_CLIENTES
WHERE CIDADE IN ('Rio de Janeiro', 'Sao Paulo')
	AND IDADE BETWEEN 20 AND 25;

SELECT *
FROM TABELA_DE_CLIENTES
WHERE NOME LIKE '%SILVA%'

SELECT *
FROM TABELA_DE_PRODUTOS
WHERE SABOR IN ('Lima/Limao', 'Morango/Limao')

SELECT *
FROM TABELA_DE_PRODUTOS
WHERE SABOR LIKE '%Limao'

SELECT *
FROM TABELA_DE_PRODUTOS
WHERE SABOR LIKE '%Maca%'


SELECT *
FROM TABELA_DE_PRODUTOS
WHERE SABOR LIKE '%Morango%'
