SELECT *
FROM TABELA_DE_CLIENTES
WHERE 1 = 1;

SELECT  *
FROM TABELA_DE_CLIENTES
WHERE 1 = 0;

SELECT *
FROM TABELA_DE_PRODUTOS
WHERE CODIGO_DO_PRODUTO = '1002767';

SELECT *
FROM TABELA_DE_PRODUTOS
WHERE SABOR = 'Laranja';

-- Colation de case insensitive
SELECT *
FROM TABELA_DE_PRODUTOS
WHERE EMBALAGEM = 'pet';


SELECT *
FROM TABELA_DE_PRODUTOS
WHERE PRECO_DE_LISTA > 10;

SELECT *
FROM TABELA_DE_PRODUTOS
WHERE PRECO_DE_LISTA BETWEEN 5 AND 10;

SELECT *
FROM TABELA_DE_CLIENTES
WHERE IDADE != 18;

