SELECT DISTINCT EMBALAGEM
FROM TABELA_DE_PRODUTOS
WHERE SABOR = 'Maca'

SELECT DISTINCT SABOR
FROM TABELA_DE_PRODUTOS;

SELECT TOP 5 *
FROM TABELA_DE_PRODUTOS
WHERE SABOR = 'Maca'

SELECT TOP(10) *
FROM NOTAS_FISCAIS
WHERE DATA_VENDA = '2017-10-01'

SELECT *
FROM TABELA_DE_CLIENTES
ORDER BY NOME ASC, BAIRRO DESC

SELECT *
FROM TABELA_DE_PRODUTOS
ORDER BY PRECO_DE_LISTA DESC

SELECT *
FROM TABELA_DE_PRODUTOS
ORDER BY EMBALAGEM, NOME_DO_PRODUTO

SELECT TOP 5 *
FROM TABELA_DE_PRODUTOS
ORDER BY PRECO_DE_LISTA DESC

/* DESAFIO */
SELECT *
FROM TABELA_DE_PRODUTOS
WHERE NOME_DO_PRODUTO = 'Linha Refrescante - 1 Litro - Morango/Limao'

SELECT TOP 1 *
FROM ITENS_NOTAS_FISCAIS
WHERE CODIGO_DO_PRODUTO = 1101035
ORDER BY QUANTIDADE DESC
/*********/

SELECT EMBALAGEM, SUM(PRECO_DE_LISTA) AS [Soma], AVG(PRECO_DE_LISTA) AS [Media]
FROM TABELA_DE_PRODUTOS
GROUP BY EMBALAGEM

SELECT CIDADE, AVG(IDADE) AS [Media Idades], SUM(LIMITE_DE_CREDITO) AS [Soma Limite Credito]
FROM TABELA_DE_CLIENTES
GROUP BY CIDADE
ORDER BY CIDADE

SELECT CIDADE, BAIRRO, AVG(IDADE) AS [Media Idades]
FROM TABELA_DE_CLIENTES
GROUP BY CIDADE, BAIRRO
ORDER BY BAIRRO DESC

SELECT CIDADE, COUNT(*) AS [Quantidade]
FROM TABELA_DE_CLIENTES
GROUP BY CIDADE

SELECT EMBALAGEM, COUNT(*) AS [Quantidade]
FROM TABELA_DE_PRODUTOS
WHERE SABOR = 'Laranja'
GROUP BY EMBALAGEM

/* DESAFIO */
SELECT CODIGO_DO_PRODUTO, COUNT(*)
FROM ITENS_NOTAS_FISCAIS
WHERE CODIGO_DO_PRODUTO = 1101035
    AND QUANTIDADE = 99
GROUP BY CODIGO_DO_PRODUTO
/***********/

SELECT ESTADO, SUM(LIMITE_DE_CREDITO) AS [Credito]
FROM TABELA_DE_CLIENTES
GROUP BY ESTADO
HAVING SUM(LIMITE_DE_CREDITO) > 900000

SELECT EMBALAGEM, MAX(PRECO_DE_LISTA) AS [Maior Preco], MIN(PRECO_DE_LISTA) AS [Menor Preco]
FROM TABELA_DE_PRODUTOS
WHERE PRECO_DE_LISTA >= 10
GROUP BY EMBALAGEM
HAVING MAX(PRECO_DE_LISTA) != MIN(PRECO_DE_LISTA)

/* DESAFIO */
SELECT CODIGO_DO_PRODUTO, SUM(QUANTIDADE) AS [Qtde Vendas]
FROM ITENS_NOTAS_FISCAIS
GROUP BY CODIGO_DO_PRODUTO
HAVING SUM(QUANTIDADE) > 394000
ORDER BY SUM(QUANTIDADE)
/***********/

SELECT NOME_DO_PRODUTO, PRECO_DE_LISTA,
       CASE
           WHEN PRECO_DE_LISTA > 12 THEN 'Produto Caro'
           WHEN PRECO_DE_LISTA >= 7 AND PRECO_DE_LISTA < 12 THEN 'Produto em Conta'
           ELSE 'Produto Barato'
       END AS [Classificação]
FROM TABELA_DE_PRODUTOS
-- WHERE SABOR = 'Manga'
ORDER BY [Classificação]

SELECT CASE
           WHEN PRECO_DE_LISTA > 12 THEN 'Produto Caro'
           WHEN PRECO_DE_LISTA >= 7 AND PRECO_DE_LISTA < 12 THEN 'Produto em Conta'
           ELSE 'Produto Barato'
       END AS [Classificação], COUNT(*) AS [Quantidade]
FROM TABELA_DE_PRODUTOS
GROUP BY CASE
             WHEN PRECO_DE_LISTA > 12 THEN 'Produto Caro'
             WHEN PRECO_DE_LISTA >= 7 AND PRECO_DE_LISTA < 12 THEN 'Produto em Conta'
             ELSE 'Produto Barato'
         END

/* DESAFIO */
SELECT NOME,
       CASE
           WHEN LIMITE_DE_CREDITO >= 150000 THEN 'Cliente grande'
           WHEN LIMITE_DE_CREDITO BETWEEN 110000 AND 149999 THEN 'Cliente médio'
           ELSE 'Cliente pequeno'
       END AS [Classificação]
FROM TABELA_DE_CLIENTES
/***********/
