-- CREATE VIEW vwAleatorio AS SELECT RAND() AS RAND_VALUE;

CREATE FUNCTION numeroAleatorioEntreValores(@VALOR_MINIMO INT, @VALOR_MAXIMO INT)
RETURNS INT
AS BEGIN
	RETURN ROUND(((@VALOR_MAXIMO - @VALOR_MINIMO - 1) * (SELECT RAND_VALUE FROM vwAleatorio) + @VALOR_MINIMO), 0);
END










/* -- DESAFIO --
CREATE FUNCTION fFaturamentoPorBairro(@BAIRRO VARCHAR(50))
RETURNS FLOAT
AS BEGIN
	DECLARE @valorFat FLOAT;

	SELECT @valorFat = ROUND(SUM(ISNULL(NI.QUANTIDADE, 0) + ISNULL(NI.PREÇO, 0)), 2)
	FROM [NOTAS FISCAIS] NF
	INNER JOIN [ITENS NOTAS FISCAIS] NI ON NI.NUMERO = NF.NUMERO
	INNER JOIN [TABELA DE CLIENTES] C ON C.CPF = NF.CPF
	WHERE UPPER(C.BAIRRO) = UPPER(@BAIRRO);

	RETURN @valorFat;
END

-- SELECT dbo.fFaturamentoPorBairro('Tijuca')
*/
