/*
CREATE PROCEDURE calculaIdade
AS
BEGIN
	UPDATE [TABELA DE CLIENTES] SET IDADE = DATEDIFF(YEAR, [DATA DE NASCIMENTO], GETDATE());
END
*/

SELECT tdc.CPF, tdc.NOME, tdc.[DATA DE NASCIMENTO], tdc.IDADE, DATEDIFF(YEAR, tdc.[DATA DE NASCIMENTO], GETDATE())
FROM [TABELA DE CLIENTES] tdc

INSERT INTO [TABELA DE CLIENTES]
(CPF, NOME, [ENDERECO 1], BAIRRO, CIDADE, ESTADO, CEP, [DATA DE NASCIMENTO], IDADE, SEXO, [LIMITE DE CREDITO], [VOLUME DE COMPRA], [PRIMEIRA COMPRA])
VALUES
('123123123', 'JOAO MACHADO', 'RUA PROJETADA A', 'MADUREIRA', 'Rio de Janeiro', 'RJ', '20000', '2000-01-01', 10, 'M', 12000, 12000, 1)
