CREATE FUNCTION valorFaturamentoNota(@NOTA INT)
RETURNS FLOAT
AS BEGIN
	DECLARE @FATURAMENTO FLOAT;

	SELECT @FATURAMENTO = SUM(QUANTIDADE * PREÇO)
	FROM [ITENS NOTAS FISCAIS]
	WHERE NUMERO = @NOTA;

	RETURN @FATURAMENTO;
END

SELECT nf.NUMERO, dbo.valorFaturamentoNota(nf.NUMERO) AS [Valor Nota]
FROM [NOTAS FISCAIS] nf


